apiVersion: v1
kind: Service
metadata:
  name: limoneno-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
      app.kubernetes.io/name: